version: 2
updates:
  # PHP dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependency"
      - "php"
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    assignees:
      - "dependabot"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependency"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 