name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, json, pdo, curl
          coverage: pcov
          tools: composer:v2, phpunit, php-cs-fixer, phpstan

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standards
        run: vendor/bin/phpcs --standard=phpcs.xml.dist src tests

      - name: Run static analysis
        run: vendor/bin/phpstan analyse src tests --level=5

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  laravel-tests:
    name: Laravel ${{ matrix.laravel-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
        laravel-version: ['8.*', '9.*', '10.*', '11.*', '12.*']
        exclude:
          # Laravel 8 requires PHP < 8.2
          - php-version: '8.2'
            laravel-version: '8.*'
          - php-version: '8.3'
            laravel-version: '8.*'
          # Laravel 9 requires PHP < 8.3
          - php-version: '8.3'
            laravel-version: '9.*'
          # Laravel 12 requires PHP >= 8.2
          - php-version: '8.0'
            laravel-version: '12.*'
          - php-version: '8.1'
            laravel-version: '12.*'

          # Laravel 10 requires PHP ^8.1
          - php-version: '8.0'
            laravel-version: '10.*'

          # Laravel 11 requires PHP ^8.2
          - php-version: '8.0'
            laravel-version: '11.*'
          - php-version: '8.1'
            laravel-version: '11.*'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, json, pdo, curl
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.laravel-version }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress

      - name: Run Laravel tests
        run: vendor/bin/phpunit tests/Laravel

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict