name: Create Release and Notify Packagist

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on tags like v1.0.0, v0.2.1, etc.

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create GitHub releases and for changelog generator to read commit history

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog generator to access full commit history

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Or your desired PHP version
          extensions: mbstring, xml, ctype, iconv, json, pdo, curl # Common extensions
          tools: composer:v2 # Use Composer v2

      - name: Validate tag format
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid tag format. Tag must be in the format vX.Y.Z (e.g., v1.0.0)."
            exit 1
          fi
        shell: bash

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }} # CORRECTED: Changed 'token' to 'myToken'
          base-ref: 'v0.1.0' # Set this to your actual earliest tag or the tag you want to compare against
          head-ref: ${{ github.ref }} # The current tag being processed

      - name: Create package archive (for GitHub Release asset)
        run: |
          mkdir -p build
          zip -r build/google-trends-php-sdk-${{ github.ref_name }}.zip . -x ".git/*" ".github/*" "tests/*" "build/*" "vendor/*"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This action (softprops) uses 'token'
          name: Release ${{ github.ref_name }}
          body: |
            ## Google Trends PHP SDK ${{ github.ref_name }}
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            To install this version:
            \`\`\`bash
            composer require nao-30/google-trends-php-sdk:${{ github.ref_name }}
            \`\`\`
            Or for the latest stable version:
            \`\`\`bash
            composer require nao-30/google-trends-php-sdk
            \`\`\`
          files: |
            build/google-trends-php-sdk-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
